<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 DoubleCup.glb -s -u -k -D
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useSuspense } from '@threlte/extras'

  export const ref = new Group()

  const suspend = useSuspense()

  const gltf = suspend(useGltf('/src/lib/models/DoubleCup.glb'))

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Lean_(REMADE_32821)" rotation={[-Math.PI / 2, 0, 1.94]} scale={0.31}>
      <T.Mesh
        name="Lean_Low__0"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Lean_Low__0.geometry}
        material={gltf.materials['Scene_-_Root']}
        scale={7}
      />
      <T.Mesh
        name="Lean_Low__0_1"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Lean_Low__0_1.geometry}
        material={gltf.materials.leeeen}
        scale={7}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
