<section style="margin-top: -100px;background-color:white;" class="relative h-screen flex flex-col items-center justify-center text-center">
    <div class="container pt-10">
        THE LEAN CONTRACT, SUPPORTING WEBSITES, AND ALL OTHER INTERFACES (THE SOFTWARE) IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
        LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
        
        BY INTERACTING WITH THE SOFTWARE YOU ARE ASSERTING THAT YOU BEAR ALL THE RISKS ASSOCIATED WITH DOING SO. AN INFINITE NUMBER OF UNPREDICTABLE THINGS MAY OCCUR WHICH COULD POTENTIALLY RESULT IN LOSS AND FAILURE, AND BY INTERACTING WITH THE SOFTWARE YOU ARE ASSERTING THAT YOU AGREE THERE IS NO RECOURSE AVAILABLE AND YOU WILL NOT SEEK IT.
        
        INTERACTING WITH THE SOFTWARE IS NOT AN INVESTMENT AND SHALL NOT BE CONSIDERED A SHARED ENTERPRISE, YOU SHALL HAVE NO EXPECTATION OF PROFIT OR ANY TYPE OF SUCCESS FROM THE WORK OF OTHER PEOPLE.
    </div>
    
</section>
